# Workaround necessary for pnpm. Unfortunately netlify doesn't support it out of the box like vercel
[build.environment]
  # This makes npm install not fail as --version overrides the install command
  NPM_FLAGS = "--version"
[build]
  # After the "successful" install, we run pnpm
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
  publish = "build"