# PNPM isn't natively supported by netlify, so we need to do these two workarounds:
[build.environment]
  # 1. This makes npm install not fail as --version overrides the install command
  NPM_FLAGS = "--version"
[build]
  # 2. After the "successful" install, we run pnpm
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
  publish = "build"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"